---
version: '2'
services:
  common:
    build: "."
    environment:
      APP_ENV: development
  app:
    extends:
      service: common
    ports:
    - 8000:8000
    command: "/app/scripts/start.sh"
